CREATE TABLE tbContador(
UUID_CONTADOR VARCHAR2(100),
NOMBRE_CONTADOR VARCHAR2(50),
EDAD_CONTADOR INT,
PESO_CONTADOR INT,
CORREO_CONTADOR VARCHAR2(100)
);

//Cambié el NUMBER a INT por que me daba error y con INT ya funcionó.

SELECT * FROM tbContador;
